trigger: none

resources:
- repo: self

variables:
- group: cyan
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Deploy Go client app

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -x
          az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
          helm upgrade --install -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-client-go-production deploy/charts/client-go --set apiServerURL=$API_SERVER_URL_PRODUCTION,image.repository=${ACR_NAME}.azurecr.io/clientgo --reuse-values
          helm upgrade --install -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-client-go-staging deploy/charts/client-go --set apiServerURL=$API_SERVER_URL_STAGING,image.repository=${ACR_NAME}.azurecr.io/clientgo --reuse-values