trigger: none

resources:
- repo: self

variables:
- group: cyan
- name: vmImageName
  value: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Deploy to Staging

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -x
          az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
          #
          # Get current production slot value, then configure the
          # script to deploy to the other slot
          #                
          productionSlot=$(helm get values -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-api-server | awk '/productionSlot/{print $2}')
          if [ $productionSlot == "blue" ]; then
              stagingSlot="green"
          else
              stagingSlot="blue"
          fi
          helm upgrade -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-api-server deploy/charts/server --set $stagingSlot.enabled=true,$stagingSlot.tag=$STAGING_TAG --reuse-values
