trigger: none

resources:
- repo: self

variables:
- group: cyan
- name: vmImageName
  value: 'ubuntu-latest'

stages:
- stage: Deploy
  displayName: Setup Staging Blue / Green Environment

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -x
          #
          # Deploy server applications to blue / green environments
          #
          az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
          helm install -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-api-server deploy/charts/server --set blue.tag=$PRODUCTION_TAG,green.tag=$STAGING_TAG,productionSlot=blue,image.repository=${ACR_NAME}.azurecr.io/simpleapi,ingress.type=$INGRESS_TYPE,ingress.hostName=$API_SERVER
          #
          # Deploy client applications for production and staging
          #
          helm install -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-client-go-production deploy/charts/client-go --set apiServerURL=http://$API_SERVER,image.repository=${ACR_NAME}.azurecr.io/clientgo
          helm install -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-client-go-staging deploy/charts/client-go --set apiServerURL=http://staging.$API_SERVER,image.repository=${ACR_NAME}.azurecr.io/clientgo
