trigger: none

resources:
- repo: self

variables:
- group: cyan
- name: vmImageName
  value: 'ubuntu-latest'
  
stages:
- stage: Deploy
  displayName: Clean up Staging Blue / Green Environment

  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: $(vmImageName)
    steps:
    - checkout: self
    - task: HelmInstaller@1
      inputs:
        helmVersionToInstall: 'latest'
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'AzureServiceConnection'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          set -x
          az aks get-credentials -g $AKS_RESOURCE_GROUP -n $AKS_NAME
          helm uninstall -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-api-server
          helm uninstall -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-client-go-production
          helm uninstall -n $DEPLOYMENT_NAME ${DEPLOYMENT_NAME}-client-go-staging