{{ if .Values.blue.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "server.fullname" . }}-blue
  labels:
    {{- include "server.labels" . | nindent 4 }}
    slot: blue
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "server.selectorLabels" . | nindent 6 }}
      slot: blue
  template:
    metadata:
      labels:
        {{- include "server.selectorLabels" . | nindent 8 }}
        slot: blue
    spec:
      serviceAccountName: {{ include "server.serviceAccountName" . }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.blue.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle: 
            preStop:
              httpGet:
                path: /api/podTerminate
                port: 3000
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/getVersion
              port: http
          readinessProbe:
            httpGet:
              path: /api/getVersion
              port: http
{{ end }}