on: [push]
name: Azure ARM
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - run: az account list -o table
    - run: az group list -o table

    - uses: Azure/CLI@v1
      with:
        inlineScript: |
          #!/bin/bash
          az group create --name aks-qrbvt-rg --location westeurope
          
      # Deploy Bicep file
    - name: deploy
      uses: azure/arm-deploy@v1
      with:
        resourceGroupName: /subscriptions/808121c2-95b0-4e15-8dbc-cb6de76a956a/resourceGroups/aks-qrbvt-rg
        template: ./bicep/aks-deploy.bicep
        parameters: name=gatest
        failOnStdErr: false
